services:
  api:
    build: .
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - HOST_NAME=${HOSTNAME}
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: always
